Update plot_helpers.py
Line 80: for i, (yy, cycle) in enumerate(zip(unique_y, current_cycler())):
threw an exception:
TypeError: 'Cycler' object is not callable
since current_cycler is just a plain variable.